[project]
name = "uncertainty_engine"
version = "0.0.1"
description = "SDK for the Uncertainty Engine"
authors = [
    {name = "digiLab Solutions Ltd.",email = "info@digilab.co.uk"}
]
maintainers = [
    {name = "Jamie Donald-McCann",email = "jamie@digilab.co.uk"}
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
