# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.api.account_records_resource import AccountRecordsResource


class TestAccountRecordsResource(unittest.TestCase):
    """AccountRecordsResource unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountRecordsResource()

    def tearDown(self) -> None:
        pass

    def test_delete_account_record(self) -> None:
        """Test case for delete_account_record

        Delete Account Record
        """
        pass

    def test_get_account_record(self) -> None:
        """Test case for get_account_record

        Get Account Record Id
        """
        pass

    def test_get_account_record_email(self) -> None:
        """Test case for get_account_record_email

        Get Account Record Email
        """
        pass

    def test_get_account_record_projects(self) -> None:
        """Test case for get_account_record_projects

        Get Account Record Projects
        """
        pass

    def test_get_account_records(self) -> None:
        """Test case for get_account_records

        Get Account Records
        """
        pass

    def test_post_account_record(self) -> None:
        """Test case for post_account_record

        Post Account Record
        """
        pass


if __name__ == '__main__':
    unittest.main()
