# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.update_workflow_version_request import UpdateWorkflowVersionRequest

class TestUpdateWorkflowVersionRequest(unittest.TestCase):
    """UpdateWorkflowVersionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWorkflowVersionRequest:
        """Test UpdateWorkflowVersionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWorkflowVersionRequest`
        """
        model = UpdateWorkflowVersionRequest()
        if include_optional:
            return UpdateWorkflowVersionRequest(
                workflow_version_record_updates = None,
                workflow = None
            )
        else:
            return UpdateWorkflowVersionRequest(
        )
        """

    def testUpdateWorkflowVersionRequest(self):
        """Test UpdateWorkflowVersionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
