# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.api.templates_resource import TemplatesResource


class TestTemplatesResource(unittest.TestCase):
    """TemplatesResource unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesResource()

    def tearDown(self) -> None:
        pass

    def test_delete_workflow_template(self) -> None:
        """Test case for delete_workflow_template

        Delete Workflow Template
        """
        pass

    def test_get_workflow_template_record(self) -> None:
        """Test case for get_workflow_template_record

        Get Workflow Template
        """
        pass

    def test_get_workflow_template_records(self) -> None:
        """Test case for get_workflow_template_records

        Get Workflow Templates
        """
        pass

    def test_workflow_template(self) -> None:
        """Test case for workflow_template

        Workflow Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
