# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.resource_version_record_input import ResourceVersionRecordInput

class TestResourceVersionRecordInput(unittest.TestCase):
    """ResourceVersionRecordInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceVersionRecordInput:
        """Test ResourceVersionRecordInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceVersionRecordInput`
        """
        model = ResourceVersionRecordInput()
        if include_optional:
            return ResourceVersionRecordInput(
                id = None,
                name = '',
                project_id = None,
                resource_id = None,
                owner_id = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location = resource_api.models.resource_location.ResourceLocation(
                    id = null, 
                    storage_type = '', 
                    config = resource_api.models.config.Config(), )
            )
        else:
            return ResourceVersionRecordInput(
                name = '',
                owner_id = None,
        )
        """

    def testResourceVersionRecordInput(self):
        """Test ResourceVersionRecordInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
