# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.workflow_record_input import WorkflowRecordInput

class TestWorkflowRecordInput(unittest.TestCase):
    """WorkflowRecordInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowRecordInput:
        """Test WorkflowRecordInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowRecordInput`
        """
        model = WorkflowRecordInput()
        if include_optional:
            return WorkflowRecordInput(
                id = None,
                name = '',
                project_id = None,
                owner_id = None,
                versions = [
                    null
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_locked = True
            )
        else:
            return WorkflowRecordInput(
                name = '',
                owner_id = None,
        )
        """

    def testWorkflowRecordInput(self):
        """Test WorkflowRecordInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
