# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.workflow_template_response import WorkflowTemplateResponse

class TestWorkflowTemplateResponse(unittest.TestCase):
    """WorkflowTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowTemplateResponse:
        """Test WorkflowTemplateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowTemplateResponse`
        """
        model = WorkflowTemplateResponse()
        if include_optional:
            return WorkflowTemplateResponse(
                workflow_template_record = resource_api.models.workflow_template_record.WorkflowTemplateRecord(
                    _id = '', 
                    name = '', 
                    description = '', 
                    complexity = 'simple', 
                    is_new = True, 
                    image_src = '', 
                    location = resource_api.models.resource_location.ResourceLocation(
                        id = null, 
                        storage_type = '', 
                        config = resource_api.models.config.Config(), ), ),
                workflow_template = resource_api.models.workflow_template.Workflow Template()
            )
        else:
            return WorkflowTemplateResponse(
                workflow_template_record = resource_api.models.workflow_template_record.WorkflowTemplateRecord(
                    _id = '', 
                    name = '', 
                    description = '', 
                    complexity = 'simple', 
                    is_new = True, 
                    image_src = '', 
                    location = resource_api.models.resource_location.ResourceLocation(
                        id = null, 
                        storage_type = '', 
                        config = resource_api.models.config.Config(), ), ),
                workflow_template = resource_api.models.workflow_template.Workflow Template(),
        )
        """

    def testWorkflowTemplateResponse(self):
        """Test WorkflowTemplateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
