# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.post_account_record_request import PostAccountRecordRequest

class TestPostAccountRecordRequest(unittest.TestCase):
    """PostAccountRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAccountRecordRequest:
        """Test PostAccountRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAccountRecordRequest`
        """
        model = PostAccountRecordRequest()
        if include_optional:
            return PostAccountRecordRequest(
                account_record = resource_api.models.account_record.AccountRecord(
                    _id = null, 
                    email = '', 
                    name = '', 
                    phone = '', 
                    status = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return PostAccountRecordRequest(
                account_record = resource_api.models.account_record.AccountRecord(
                    _id = null, 
                    email = '', 
                    name = '', 
                    phone = '', 
                    status = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testPostAccountRecordRequest(self):
        """Test PostAccountRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
