# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.get_account_records_response import GetAccountRecordsResponse

class TestGetAccountRecordsResponse(unittest.TestCase):
    """GetAccountRecordsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountRecordsResponse:
        """Test GetAccountRecordsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountRecordsResponse`
        """
        model = GetAccountRecordsResponse()
        if include_optional:
            return GetAccountRecordsResponse(
                account_records = [
                    resource_api.models.account_record.AccountRecord(
                        _id = '', 
                        email = '', 
                        name = '', 
                        phone = '', 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return GetAccountRecordsResponse(
                account_records = [
                    resource_api.models.account_record.AccountRecord(
                        _id = '', 
                        email = '', 
                        name = '', 
                        phone = '', 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testGetAccountRecordsResponse(self):
        """Test GetAccountRecordsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
