# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.project_roles import ProjectRoles

class TestProjectRoles(unittest.TestCase):
    """ProjectRoles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectRoles(self):
        """Test ProjectRoles"""
        # inst = ProjectRoles()

if __name__ == '__main__':
    unittest.main()
