# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.resource_response import ResourceResponse

class TestResourceResponse(unittest.TestCase):
    """ResourceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceResponse:
        """Test ResourceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceResponse`
        """
        model = ResourceResponse()
        if include_optional:
            return ResourceResponse(
                resource_record = resource_api.models.resource_record.ResourceRecord(
                    _id = '', 
                    name = '', 
                    project_id = '', 
                    owner_id = '', 
                    versions = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_locked = True, )
            )
        else:
            return ResourceResponse(
                resource_record = resource_api.models.resource_record.ResourceRecord(
                    _id = '', 
                    name = '', 
                    project_id = '', 
                    owner_id = '', 
                    versions = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_locked = True, ),
        )
        """

    def testResourceResponse(self):
        """Test ResourceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
