# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.api.workflows_resource import WorkflowsResource


class TestWorkflowsResource(unittest.TestCase):
    """WorkflowsResource unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsResource()

    def tearDown(self) -> None:
        pass

    def test_delete_workflow_record(self) -> None:
        """Test case for delete_workflow_record

        Delete Workflow
        """
        pass

    def test_delete_workflow_version_record(self) -> None:
        """Test case for delete_workflow_version_record

        Delete Workflow Version
        """
        pass

    def test_get_latest_workflow_version(self) -> None:
        """Test case for get_latest_workflow_version

        Get Latest Workflow Version
        """
        pass

    def test_get_project_workflow_records(self) -> None:
        """Test case for get_project_workflow_records

        Get Project Workflow Records
        """
        pass

    def test_get_workflow_record(self) -> None:
        """Test case for get_workflow_record

        Get Workflow Record
        """
        pass

    def test_get_workflow_version(self) -> None:
        """Test case for get_workflow_version

        Get Workflow Version
        """
        pass

    def test_get_workflow_version_records(self) -> None:
        """Test case for get_workflow_version_records

        Get Workflow Version Records
        """
        pass

    def test_post_workflow_record(self) -> None:
        """Test case for post_workflow_record

        Post Workflow Record
        """
        pass

    def test_post_workflow_version(self) -> None:
        """Test case for post_workflow_version

        Post Workflow Version
        """
        pass

    def test_put_workflow_version(self) -> None:
        """Test case for put_workflow_version

        Put Workflow Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
