# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.api.resources_resource import ResourcesResource


class TestResourcesResource(unittest.TestCase):
    """ResourcesResource unit test stubs"""

    def setUp(self) -> None:
        self.api = ResourcesResource()

    def tearDown(self) -> None:
        pass

    def test_delete_resource_record(self) -> None:
        """Test case for delete_resource_record

        Delete Resource
        """
        pass

    def test_delete_resource_version_record(self) -> None:
        """Test case for delete_resource_version_record

        Delete Resource Version
        """
        pass

    def test_get_latest_resource_version(self) -> None:
        """Test case for get_latest_resource_version

        Get Latest Resource Version
        """
        pass

    def test_get_project_resource_records(self) -> None:
        """Test case for get_project_resource_records

        Get Project Resource Records
        """
        pass

    def test_get_resource_record(self) -> None:
        """Test case for get_resource_record

        Get Resource Record
        """
        pass

    def test_get_resource_version(self) -> None:
        """Test case for get_resource_version

        Get Resource Version
        """
        pass

    def test_get_resource_version_records(self) -> None:
        """Test case for get_resource_version_records

        Get Resource Version Records
        """
        pass

    def test_patch_resource_version(self) -> None:
        """Test case for patch_resource_version

        Patch Resource Version
        """
        pass

    def test_post_resource_record(self) -> None:
        """Test case for post_resource_record

        Post Resource Record
        """
        pass

    def test_post_resource_version(self) -> None:
        """Test case for post_resource_version

        Post Resource Version
        """
        pass

    def test_put_upload_resource_version(self) -> None:
        """Test case for put_upload_resource_version

        Put Upload Resource Version
        """
        pass


if __name__ == '__main__':
    unittest.main()
