# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.api.auth_resource import AuthResource


class TestAuthResource(unittest.TestCase):
    """AuthResource unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthResource()

    def tearDown(self) -> None:
        pass

    def test_get_tokens(self) -> None:
        """Test case for get_tokens

        Get Tokens
        """
        pass

    def test_refresh_token(self) -> None:
        """Test case for refresh_token

        Refresh Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
