# coding: utf-8

"""
    Uncertainty Engine Resource Service API

    Resource management API for the twinLab platform.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from resource_api.models.post_resource_record_request import PostResourceRecordRequest

class TestPostResourceRecordRequest(unittest.TestCase):
    """PostResourceRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostResourceRecordRequest:
        """Test PostResourceRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostResourceRecordRequest`
        """
        model = PostResourceRecordRequest()
        if include_optional:
            return PostResourceRecordRequest(
                resource_record = resource_api.models.resource_record.ResourceRecord(
                    _id = null, 
                    name = '', 
                    project_id = null, 
                    owner_id = null, 
                    versions = [
                        null
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_locked = True, )
            )
        else:
            return PostResourceRecordRequest(
                resource_record = resource_api.models.resource_record.ResourceRecord(
                    _id = null, 
                    name = '', 
                    project_id = null, 
                    owner_id = null, 
                    versions = [
                        null
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    is_locked = True, ),
        )
        """

    def testPostResourceRecordRequest(self):
        """Test PostResourceRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
