#!/bin/sh
set -e

echo "Running continous integration..."

echo "[1/3] Running code formatter..."
sh ./CI/run_formatter_code.sh

echo "[2/3] Running linter..."
sh ./CI/run_linter.sh

echo "[3/3] Running unit tests..."
sh ./CI/run_tests_unit.sh