name: End-to-end tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 09,17 * * *" # Run every day at 9:00 and 17:00

jobs:
  dev:
    uses: ./.github/workflows/e2e-environment.yaml
    with:
      ue-environment: dev
    secrets:
      ue-password: ${{ secrets.UE_DEV_PASSWORD }}
      ue-username: ${{ secrets.UE_DEV_USERNAME }}

  prod:
    uses: ./.github/workflows/e2e-environment.yaml
    with:
      ue-environment: prod
    secrets:
      ue-password: ${{ secrets.UE_PROD_PASSWORD }}
      ue-username: ${{ secrets.UE_PROD_USERNAME }}
