name: Unit + functional tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UE_USERNAME: ${{ secrets.UE_USER_EMAIL }}

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run unit tests
        run: sh CI/run_tests_unit.sh

      - name: Run functional tests
        run: sh CI/run_tests_functional.sh
